include:
  - infra.yaml

services:
  web:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
